### ISSUE TITLE
Diagram out the logical flow

### ISSUE THREAD

**Issue by gingeleski** [ashleylizg/spotify-artists#4]
Diagram out the logical flow of your program. I forget whether you got Visio Pro or not.

Figure out what this is actually going to do, nailing down the logic as much as possible beforehand.

https://support.office.com/en-us/article/create-a-basic-flowchart-e207d975-4a51-4bfa-a356-eeec314bd276

This should precede **#3** and probably also **#1**.

**Comment by ashleylizg** [comment]
![artist_ext_workflow](https://user-images.githubusercontent.com/35569185/65427632-bb855100-dde0-11e9-8816-2adb5b0f722c.jpg)
